# This is a basic workflow to help you get started with Actions

name: zip for release

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v6
    
      - name: move
        run: mkdir ./quark
      
      - name: checkout-quark
        uses: actions/checkout@v6
        with:
          repository: "VazkiiMods/Quark"
          sparse-checkout: |
            src/main/resources/assets/quark/textures/quark_variant_chests
          sparse-checkout-cone-mode: true
          path: "quark"
          
      - run: git sparse-checkout list
        working-directory: quark
          
      # Runs a single command using the runners shell
      - name: move
        run: |
          mkdir ./assets
          mkdir ./assets/quark
          mv ./models ./assets/quark/models
          mv ./blockstates ./assets/quark/blockstates
          zip -r bluemap-quark.zip ./assets
      
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: bluemap-quark.zip
          
